[build]
command = "npm install && npm run build"
publish = "dist"

[env.production]
VITE_API_URL = "https://tryon-backend-ayjb.onrender.com"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
